webtalk_init -webtalk_dir /home/qdouarre/Documents/4A/BE_ethernet/BE_controleur_ethernet/Transmission/Transmission.sim/sim_1/behav/xsim/xsim.dir/test_transmission_ethernet_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Thu Apr 21 22:06:19 2022" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2018.2 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2258646" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "LIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "db7f0987-d580-4df3-b364-f5511601c0c6" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "71c93a757db54a33a29ff74552ff7135" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "116" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Ubuntu" -context "user_environment"
webtalk_add_data -client project -key os_release -value "Ubuntu 20.04.4 LTS" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Xeon(R) Silver 4216 CPU @ 2.10GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "900.000 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "2" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "134.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "40 us" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "2" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "0.04_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "114420_KB" -context "xsim\\usage"
webtalk_transmit -clientid 3448894074 -regid "" -xml /home/qdouarre/Documents/4A/BE_ethernet/BE_controleur_ethernet/Transmission/Transmission.sim/sim_1/behav/xsim/xsim.dir/test_transmission_ethernet_behav/webtalk/usage_statistics_ext_xsim.xml -html /home/qdouarre/Documents/4A/BE_ethernet/BE_controleur_ethernet/Transmission/Transmission.sim/sim_1/behav/xsim/xsim.dir/test_transmission_ethernet_behav/webtalk/usage_statistics_ext_xsim.html -wdm /home/qdouarre/Documents/4A/BE_ethernet/BE_controleur_ethernet/Transmission/Transmission.sim/sim_1/behav/xsim/xsim.dir/test_transmission_ethernet_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
